[settings]
install_before = "3d"

[tools]
claude = "latest"
codex = "latest"
delta = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
gh = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
